apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xh4ihg4by-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:4740c5a04dd43e0a0c6bc488bcdbcbbcfa860a6d@sha256:c0f725f2f5530949d1a8c76263ce6f002c1a1dd13698ee0b9169cf6d6673b6b7
          name: container-image
